[profile.default]
fail-fast = false
retries = 0
slow-timeout = { period = "60s", terminate-after = 2 }
status-level = "fail"
final-status-level = "slow"

[profile.ci]
fail-fast = false
retries = 0
slow-timeout = { period = "60s", terminate-after = 2 }
status-level = "fail"
final-status-level = "slow"
