import { APIExperimentRun } from "../../types";
import {
  CommitGroup,
  ProjectHistoryItemType,
  ProjectHistoryReturn,
} from "../apiTypes";
import {
  LinkableProject,
  ReleaseDescription,
} from "../../../features/project/types";

/**
 * This type mapping is necessary because we use APIExperimentRun instead of
 * the autogenerated experiment run type elsewhere in the project
 *
 * @todo remove this
 */

export type ProjectHistoryItemItem =
  | ReleaseDescription
  | CommitGroup
  | APIExperimentRun;

type ProjectHistoryItemShared = { createdAt: string };

export type ProjectHistoryItemExperimentRun = ProjectHistoryItemShared & {
  itemType: ProjectHistoryItemType.ExperimentRun;
  item: APIExperimentRun;
};

export type ProjectHistoryItemRelease = ProjectHistoryItemShared & {
  itemType: ProjectHistoryItemType.Release;
  item: ReleaseDescription;
};

export type ProjectHistoryItemCommitGroup = ProjectHistoryItemShared & {
  itemType: ProjectHistoryItemType.CommitGroup;
  item: CommitGroup;
};

export type ProjectHistoryItem =
  | ProjectHistoryItemExperimentRun
  | ProjectHistoryItemRelease
  | ProjectHistoryItemCommitGroup;

export type ProjectHistoryReturnWithCustomItem = Omit<
  ProjectHistoryReturn,
  "items"
> & {
  items: ProjectHistoryItem[];
};

export const projectHistory = async (
  _project: LinkableProject,
  _pageToCurrent: boolean,
  _createdBefore?: string | null,
  _accessCode?: string,
  _signal?: AbortSignal,
): Promise<ProjectHistoryReturnWithCustomItem> => ({
  items: [],
  next: null,
  remaining: false,
  receivedCurrent: true,
});
