services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    command: postgres -c wal_level=logical -c max_replication_slots=4 -c max_wal_senders=4
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
