"""Build demo-data.json with real embeddings and top-k predictions.

Selects diverse examples from the test set, fetches their embeddings
via DuckDB (no full materialization), runs top-k beam search, and
writes the JSON consumed by the blog demo.

Usage:
    uv run python scripts/build_demo_examples.py
"""

import json
from pathlib import Path

import duckdb
import numpy as np

from vec2slug.training.seq2seq.predict import Seq2SeqPredictor

PROJECT = Path(__file__).parent.parent
DATA = PROJECT / "data/url/openai"
MODEL_DIR = DATA / "models/seq2seq_bpe_d384_l4_t24_eos"


def _site_root() -> Path:
    """Resolve SLUG_SITE_ROOT or fall back to HASHDOTDEV_ROOT."""
    from os import environ

    for key in ("SLUG_SITE_ROOT", "HASHDOTDEV_ROOT"):
        val = environ.get(key)
        if val:
            return Path(val)
    raise OSError(
        "Set SLUG_SITE_ROOT to the hashdotdev app root, e.g. "
        "SLUG_SITE_ROOT=/path/to/internal-sites/apps/hashdotdev"
    )


OUTPUT = _site_root() / "src/components/mdx/blog/vec2slug/demo-data.json"

# Hand-picked example slugs from the test set, chosen for topic diversity
# and a mix of prediction quality (exact, close, overgeneralized).
PICKS = [
    # Exact matches
    "can-we-live-on-mars",
    "celebrating-martin-luther-king-jr-day",
    # Close predictions
    "inuit-knowledge-sheds-light-on-climate-change",
    "debunking-myths-about-fertility-and-pregnancy",
    "whiplash-and-brain-injury",
    "scientists-trained-ai-write-poetry",
    "new-technology-may-help-neural-regeneration-afte",
    # Overgeneralized
    "shakespeare-at-davidson-middle",
    "12-things-may-not-know-waldorf-education",
    "six-new-materials-that-are-changing-commercial-construction",
]


def main():
    con = duckdb.connect()

    pred_file = str(
        DATA / "predictions/seq2seq_bpe_d384_l4_t24_eos_seq2seq_test.parquet"
    )
    corpus_file = str(DATA.parent / "corpus.parquet")
    emb_file = str(DATA / "embeddings.parquet")

    slug_list = ", ".join(f"'{s}'" for s in PICKS)

    # Fetch metadata + embeddings via DuckDB
    rows = con.sql(f"""
        SELECT
            c.id,
            c.slug AS reference_slug,
            p.predicted_slug,
            c.url,
            c.text AS source_text,
            e.embedding
        FROM '{corpus_file}' c
        JOIN '{pred_file}' p ON p.id = c.id
        JOIN '{emb_file}' e ON e.id = c.id
        WHERE c.slug IN ({slug_list})
    """).fetchall()

    print(f"Found {len(rows)} / {len(PICKS)} examples")

    # Load predictor for top-k
    predictor = Seq2SeqPredictor(MODEL_DIR, encoder="openai", device="cpu")

    examples = []
    for row in rows:
        doc_id, ref_slug, pred_slug, url, source_text, embedding_list = row
        embedding = np.array(embedding_list, dtype=np.float32).reshape(1, -1)

        # Run top-k prediction
        topk = predictor.predict_topk(embedding, k=5)[0]

        candidates = [{"slug": slug, "score": round(score, 3)} for slug, score in topk]

        # Short label from URL host + topic
        try:
            from urllib.parse import urlparse

            host = urlparse(url).hostname or ""
            host = host.replace("www.", "")
        except Exception:
            host = url

        examples.append({
            "id": ref_slug.replace("-", "_")[:30],
            "label": host,
            "source_url": url,
            "source_text": source_text.strip(),
            "reference_slug": ref_slug,
            "cached_slug": candidates[0]["slug"] if candidates else pred_slug,
            "cached_candidates": candidates,
            "embedding": [round(float(v), 6) for v in embedding_list],
        })

    # Sort for stable output
    examples.sort(key=lambda e: e["id"])

    output = {
        "_note": "Auto-generated by scripts/build_demo_examples.py. Do not edit by hand.",
        "examples": examples,
    }

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(output, indent=2))
    size_kb = OUTPUT.stat().st_size / 1024
    print(f"Wrote {len(examples)} examples to {OUTPUT} ({size_kb:.0f} KiB)")


if __name__ == "__main__":
    main()
