"""Build HuggingFace repo contents for each model variant.

Copies the skeleton from hf/, adds model-specific files, runs the ONNX
exporter if needed, and generates the README from the template. Output
lands in .hf/<repo-name>/contents/, ready for upload.

All model configuration lives in hf/models.json (single source of truth).
Eval metrics come from hf/eval.json (generated by scripts/extract_eval.py).

Usage:
    uv run scripts/extract_eval.py       # first: extract eval data
    uv run scripts/publish_hf.py         # then: build repos
    uv run scripts/publish_hf.py --dry-run
"""

import json
import shutil
import subprocess
import sys
from pathlib import Path

HF_ORG = "hashintel"
BLOG_URL = "https://hash.dev/blog/vec2slug"
REPO_URL = "https://github.com/hashintel/labs"

MODELS_PATH = Path("hf/models.json")
EVAL_PATH = Path("hf/eval.json")
SKELETON_DIR = Path("hf")
OUTPUT_ROOT = Path(".hf")

# (source name in model_dir, destination name in HF repo)
MODEL_FILES = [
    ("best.pt", "model.pt"),
    ("model.onnx", "model.onnx"),
    ("model.onnx.data", "model.onnx.data"),
    ("model.json", "model.json"),
    ("tokenizer.json", "tokenizer.json"),
    ("manifest.json", "manifest.train.json"),
    ("onnx_manifest.json", "manifest.onnx.json"),
    ("history.jsonl", "history.train.jsonl"),
]


def _format_params(n: int) -> str:
    if n >= 1_000_000:
        return f"{n / 1_000_000:.1f}M"
    if n >= 1_000:
        return f"{n / 1_000:.0f}K"
    return str(n)


def _format_size(nbytes: int) -> str:
    mib = nbytes / (1024 * 1024)
    if mib >= 1:
        return f"{mib:.1f} MiB"
    return f"{nbytes / 1024:.1f} KiB"


def _run_export(model_dir: Path, workspace: str):
    print("  Running ONNX export...")
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "vec2slug.export_onnx",
            str(model_dir),
            "--workspace",
            workspace,
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"  Export failed:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)
    print("  Export complete")


def _upload_repo(repo_name: str, commit_message: str):
    """Upload a built repo to HuggingFace Hub."""
    contents_dir = OUTPUT_ROOT / repo_name / "contents"
    repo_id = f"{HF_ORG}/{repo_name}"
    print(f"\nUploading {repo_id}...")
    result = subprocess.run(
        [
            "huggingface-cli", "upload",
            repo_id,
            str(contents_dir),
            ".",
            "--commit-message", commit_message,
        ],
    )
    if result.returncode != 0:
        print(f"Upload failed for {repo_id}", file=sys.stderr)
        sys.exit(1)


def _other_variant(repo_name: str, all_repos: list[str]) -> str | None:
    """Find the other variant in the same family."""
    for name in all_repos:
        if name != repo_name:
            return name
    return None


def build_repo(
    repo_name: str,
    config: dict,
    evaluation: dict,
    all_repos: list[str],
    *,
    dry_run: bool = False,
):
    model_dir = Path(config["model_dir"])
    output_dir = OUTPUT_ROOT / repo_name / "contents"

    print(f"\n{'[dry run] ' if dry_run else ''}Building {repo_name}")
    print(f"  Source: {model_dir}")
    print(f"  Output: {output_dir}")

    if not (model_dir / "model.onnx").exists():
        if dry_run:
            print("  Would run ONNX export")
        else:
            _run_export(model_dir, config["workspace"])

    if dry_run:
        return

    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)

    # Copy skeleton files (skip templates, directories, and data files)
    skip = {".tmpl", ".json"}
    for path in SKELETON_DIR.iterdir():
        if path.is_dir() or path.suffix in skip:
            continue
        shutil.copy2(path, output_dir / path.name)
        print(f"  Copied skeleton: {path.name}")

    for source_name, dest_name in MODEL_FILES:
        source = model_dir / source_name
        if source.exists():
            shutil.copy2(source, output_dir / dest_name)
            print(
                f"  {source_name} -> {dest_name} ({_format_size(source.stat().st_size)})"
            )
        else:
            print(f"  Skipped (not found): {source_name}")

    onnx_manifest = json.loads((model_dir / "onnx_manifest.json").read_text())

    other_repo = _other_variant(repo_name, all_repos)
    other_display = (
        other_repo.replace("vec2slug-", "vec2slug ").title() if other_repo else ""
    )

    variant_note = config.get("variant_note", "")
    if other_repo:
        variant_note += (
            f"\n\nSee also: [{other_display}]"
            f"(https://huggingface.co/{HF_ORG}/{other_repo})"
        )

    template_vars = {
        "repo_name": repo_name,
        "n_params": _format_params(evaluation["n_params"]),
        "num_layers": evaluation["num_layers"],
        "embed_dim": evaluation["embed_dim"],
        "vocab_size": evaluation["vocab_size"],
        "onnx_size": _format_size(onnx_manifest["onnx_size_bytes"]),
        "corpus_size": "2.3M",
        "eval_samples": f"{evaluation['n_samples']:,}",
        "blog_url": BLOG_URL or "TBD",
        "repo_url": REPO_URL,
        "other_variant_name": other_display,
        "other_variant_url": f"https://huggingface.co/{HF_ORG}/{other_repo}"
        if other_repo
        else "",
        "tok_f1": evaluation["tok_f1"],
        "exact_match": f"{evaluation['exact_match']:.1%}",
        "validity": f"{evaluation['validity']:.0%}",
        "vocab_diversity": f"{evaluation['vocab_diversity']:.1%}",
        "inference_speed": config.get("inference_speed", ""),
        "training_details": config.get("training_details", ""),
        "variant_note": variant_note,
    }

    template = (SKELETON_DIR / "README.md.tmpl").read_text()
    readme = template.format(**template_vars)
    (output_dir / "README.md").write_text(readme)
    print("  Generated README.md")

    print(f"  Done: {sum(1 for _ in output_dir.iterdir())} files")


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Build HF repo contents")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--model", help="Build a single model (default: all)")
    parser.add_argument(
        "--upload",
        metavar="MESSAGE",
        help="Upload to HuggingFace Hub with this commit message",
    )
    args = parser.parse_args()

    if not MODELS_PATH.exists():
        print(f"Missing {MODELS_PATH}", file=sys.stderr)
        sys.exit(1)
    if not EVAL_PATH.exists():
        print(
            f"Missing {EVAL_PATH}. Run: uv run scripts/extract_eval.py", file=sys.stderr
        )
        sys.exit(1)

    models = json.loads(MODELS_PATH.read_text())
    eval_data = json.loads(EVAL_PATH.read_text())
    all_repos = list(models.keys())

    if args.model:
        if args.model not in models:
            print(
                f"Unknown model: {args.model}. Options: {', '.join(all_repos)}",
                file=sys.stderr,
            )
            sys.exit(1)
        selected = {args.model: models[args.model]}
    else:
        selected = models

    built_repos: list[str] = []
    for repo_name, config in selected.items():
        if repo_name not in eval_data:
            print(f"No eval data for {repo_name} in {EVAL_PATH}", file=sys.stderr)
            sys.exit(1)
        build_repo(
            repo_name, config, eval_data[repo_name], all_repos, dry_run=args.dry_run
        )
        built_repos.append(repo_name)

    if args.dry_run:
        return

    if args.upload:
        for repo_name in built_repos:
            _upload_repo(repo_name, args.upload)
    else:
        print(f"\n✓ Output in {OUTPUT_ROOT}/")
        for repo_name in built_repos:
            print(
                f"  huggingface-cli upload {HF_ORG}/{repo_name}"
                f" {OUTPUT_ROOT}/{repo_name}/contents ."
            )


if __name__ == "__main__":
    main()
