[package]
name = "hash_types"
version = "0.1.0"
authors = ["HASH <careers@hash.dev>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0.53"
uuid = { version = "0.8.1", features = ["serde", "v4", "wasm-bindgen"] }
serde-aux = "0.6.1"
async-trait = "0.1.40"
