import { generateGitignore, resolveProfileInclude } from './profileinclude.js';

// ---------------------------------------------------------------------------
// Gitignore templates for whole-directory (non-include) agents
// ---------------------------------------------------------------------------

const OPENCODE_GITIGNORE = `# Generated by agentprofiles
# Regeneratable from package.json
*/node_modules/
`;

const AMP_GITIGNORE = `# Generated by agentprofiles
# Keep: settings.json, AGENTS.md, themes/
# Ignore: oauth tokens, caches, logs, temporary files

# Authentication and sensitive data
oauth/

# Caches and logs
cache/
logs/

# Temporary files
tmp/

# System files
.DS_Store
`;

const GEMINI_GITIGNORE = `# Generated by agentprofiles
# Shared Gemini state (all runtime/session data)
_shared/

# Runtime/session state per profile
*/antigravity
*/antigravity-browser-profile
*/history
*/installation_id
*/projects.json
*/settings.json.orig
*/state.json
*/tmp
*/trustedFolders.json
*/user_id
`;

const AUGMENT_GITIGNORE = `# Generated by agentprofiles
# Keep: settings.json, agents/, commands/
# Ignore: session tokens, caches, binaries, internal state, logs

# Session and authentication
.auggie.json
session.json
sessions/

# Caches and temporary files
checkpoint-documents/
task-storage/
tmp/

# Binaries and internal state
binaries/
electron-node/
auggie-path

# Logs and debugging
mcp-debug.log
mcp-server/
observability/

# System files
.DS_Store
`;

/**
 * Get the .gitignore content for an agent's content directory.
 *
 * For include-based agents (claude, codex): generates a deny-all / allow-list
 * gitignore derived from the agent's .profileinclude defaults.
 *
 * For directory-based agents: returns the static template.
 */
export function getAgentGitignore(agent: string): string {
  // Include-based agents: generate from .profileinclude
  const include = resolveProfileInclude(agent);
  if (include) {
    return generateGitignore(include);
  }

  // Directory-based agents: static templates
  switch (agent) {
    case 'opencode':
      return OPENCODE_GITIGNORE;
    case 'amp':
      return AMP_GITIGNORE;
    case 'gemini':
      return GEMINI_GITIGNORE;
    case 'augment':
      return AUGMENT_GITIGNORE;
    default:
      return '';
  }
}
