const CLAUDE_GITIGNORE = `# Generated by agentprofiles
# Shared Claude state (all runtime/session data)
_shared/

# Runtime/session state per profile
*/cache
*/debug
*/downloads
*/file-history
*/ide
*/paste-cache
*/plans
*/projects
*/session-env
*/shell-snapshots
*/statsig
*/tasks
*/telemetry
*/todos
*/history.jsonl
*/stats-cache.json

# Plugin runtime state
*/plugins/cache
*/plugins/install-counts-cache.json
*/plugins/installed_plugins.json
*/plugins/marketplaces

# Machine-specific and sensitive files
*/.DS_Store
*/.claude.json
*/.claude.json.backup
*/.claude.json.backup.*
*/settings.local.json
*/.credentials.json
`;

const OPENCODE_GITIGNORE = `# Generated by agentprofiles
# Regeneratable from package.json
*/node_modules/
`;

const AMP_GITIGNORE = `# Generated by agentprofiles
# Keep: settings.json, AGENTS.md, themes/
# Ignore: oauth tokens, caches, logs, temporary files

# Authentication and sensitive data
oauth/

# Caches and logs
cache/
logs/

# Temporary files
tmp/

# System files
.DS_Store
`;

const CODEX_GITIGNORE = `# Generated by agentprofiles
# root
*/*
!*/meta.json
!*/config.toml
!*/README.md

# rules and prompts
!*/rules/
!*/prompts/

# skills (symlinks to ~/.agents/skills/)
!*/skills/
`;

const GEMINI_GITIGNORE = `# Generated by agentprofiles
# Shared Gemini state (all runtime/session data)
_shared/

# Runtime/session state per profile
*/antigravity
*/antigravity-browser-profile
*/history
*/installation_id
*/projects.json
*/settings.json.orig
*/state.json
*/tmp
*/trustedFolders.json
*/user_id
`;

const AUGMENT_GITIGNORE = `# Generated by agentprofiles
# Keep: settings.json, agents/, commands/
# Ignore: session tokens, caches, binaries, internal state, logs

# Session and authentication
.auggie.json
session.json
sessions/

# Caches and temporary files
checkpoint-documents/
task-storage/
tmp/

# Binaries and internal state
binaries/
electron-node/
auggie-path

# Logs and debugging
mcp-debug.log
mcp-server/
observability/

# System files
.DS_Store
`;

export function getAgentGitignore(agent: string) {
  switch (agent) {
    case 'claude':
      return CLAUDE_GITIGNORE;
    case 'opencode':
      return OPENCODE_GITIGNORE;
    case 'amp':
      return AMP_GITIGNORE;
    case 'codex':
      return CODEX_GITIGNORE;
    case 'gemini':
      return GEMINI_GITIGNORE;
    case 'augment':
      return AUGMENT_GITIGNORE;
    default:
      return '';
  }
}
