/**
 * .profileinclude — allow-list format for include-based agents.
 *
 * Format:
 *   - Newline-separated paths
 *   - Lines starting with `#` (optionally preceded by whitespace) are comments
 *   - Trailing `/` denotes a directory entry
 *   - Blank lines are ignored
 *
 * Strategy:
 *   Agents that have a .profileinclude use the "inverted per-file symlink" strategy:
 *   the global config dir is left as a real directory, and only allow-listed paths
 *   inside it are symlinked to the active profile.
 *
 *   Agents without a .profileinclude use the "directory" strategy:
 *   the entire global config dir is a symlink to the active profile dir (legacy behavior).
 *
 * TODO: getDefaultProfileInclude() currently only consults inline defaults.
 *   Once content-dir override support is added, it must check
 *   contentDir/{agent}/.profileinclude first, and fall back to defaults second.
 *   Until then, user edits to the content-dir copy are not read at runtime.
 */

export interface ProfileInclude {
  /** Directory names to include (without trailing slash) */
  dirs: string[];
  /** File names/paths to include */
  files: string[];
}

/**
 * Parse a .profileinclude file's content.
 * - Ignores blank lines
 * - Strips lines where the first non-whitespace character is `#`
 * - Trailing `/` = directory entry; otherwise file entry
 * - Normalizes entries: trims whitespace, skips empty results
 */
export function parseProfileInclude(content: string): ProfileInclude {
  const dirs: string[] = [];
  const files: string[] = [];

  for (const rawLine of content.split('\n')) {
    const line = rawLine.trim();

    // Skip blank lines and comment lines (# must be first non-whitespace char)
    if (!line || line.startsWith('#')) continue;

    if (line.endsWith('/')) {
      const entry = line.slice(0, -1).trim();
      if (entry) dirs.push(entry);
    } else {
      if (line) files.push(line);
    }
  }

  return { dirs, files };
}

/**
 * Generate a deny-all / allow-list .gitignore from a ProfileInclude.
 *
 * The .gitignore lives at the agent content dir level. Profile dirs are one
 * level deeper, so all per-profile patterns use a star-slash prefix.
 * Directory entries get both a dir pattern and a double-star glob so that
 * directory contents are tracked recursively.
 */
export function generateGitignore(include: ProfileInclude): string {
  const lines: string[] = [
    '# Generated by agentprofiles from .profileinclude',
    '# Deny-all, then allow only tracked config files',
    '',
    '# Ignore everything at this level, allow profile dirs',
    '*',
    '!*/',
    '',
    '# Ignore everything inside profile dirs',
    '*/*',
    '',
    '# Allow tracked config entries (matches .profileinclude)',
  ];

  for (const file of include.files) {
    lines.push(`!*/${file}`);
  }

  for (const dir of include.dirs) {
    lines.push(`!*/${dir}/`);
    lines.push(`!*/${dir}/**`);
  }

  // Always allow agentprofiles management files
  lines.push('');
  lines.push('# Allow agentprofiles management files');
  lines.push('!*/meta.json');
  lines.push('!.profileinclude');
  lines.push('!.gitignore');

  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Inline default .profileinclude content per agent
//
// These are the CLI-shipped defaults. setup copies them to
// contentDir/{agent}/.profileinclude where the user can edit them.
//
// Keys must match keys in SUPPORTED_TOOLS.
// ---------------------------------------------------------------------------

const CLAUDE_PROFILEINCLUDE = `# claude .profileinclude
# Tracked config files for Claude Code profiles.
# Trailing / = directory. Lines starting with # are comments.
agents/
skills/
commands/
hooks/
CLAUDE.md
settings.json
settings.local.json
`;

const CODEX_PROFILEINCLUDE = `# codex .profileinclude
# Tracked config files for Codex profiles.
# Trailing / = directory. Lines starting with # are comments.
prompts/
skills/
AGENTS.md
`;

/**
 * Map of agent name → default .profileinclude content.
 * Only agents listed here use the "include" strategy.
 * Agents absent from this map use the "directory" strategy.
 */
export const DEFAULT_PROFILE_INCLUDES: Record<string, string> = {
  claude: CLAUDE_PROFILEINCLUDE,
  codex: CODEX_PROFILEINCLUDE,
};

/**
 * Get the default .profileinclude content for an agent.
 * Returns null if the agent uses the whole-directory strategy.
 */
export function getDefaultProfileInclude(agent: string): string | null {
  return DEFAULT_PROFILE_INCLUDES[agent] ?? null;
}

/**
 * Resolve the ProfileInclude for an agent from its default.
 * Returns null if the agent uses the whole-directory strategy.
 */
export function resolveProfileInclude(agent: string): ProfileInclude | null {
  const content = getDefaultProfileInclude(agent);
  if (!content) return null;
  return parseProfileInclude(content);
}

/**
 * Get the agent's symlink strategy.
 * - 'include': inverted per-file symlinks into a real global dir (claude, codex)
 * - 'directory': whole-directory symlink to the profile dir (amp, opencode, augment, etc.)
 */
export function getAgentStrategy(agent: string): 'include' | 'directory' {
  return getDefaultProfileInclude(agent) !== null ? 'include' : 'directory';
}
