#!/usr/bin/env sh
set -e

. "$(dirname -- "$0")/_/husky.sh"

echo "************************************************************************"
echo "**    Running sim-core's 'yarn lint'                                  **"
echo "**                                                                    **"
echo "**    If this fails, run 'yarn lint' for details.                     **"
echo "**    You'll need to either fix formatting ('yarn fmt'),              **"
echo "**    or fix the typescript build ('yarn lint')                      **"
echo "**                                                                    **"
echo "**    (Output is stored in .config/husky/husky.log)                   **"
echo "**    This takes about 10 seconds...                                  **"
echo "************************************************************************"

cd apps/sim-core || exit 1
yarn lint > ../../.config/husky/husky.log 2>&1;

echo "**    Formatting check success.                                       **"
echo "************************************************************************"
