name: Preflight

on:
  pull_request:
    paths:
      - ".github/workflows/preflight.yml"
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
  merge_group:

jobs:
  dependencies:
    name: Dependencies
    permissions:
      contents: read
      pull-requests: write
    uses: hashintel/.github/.github/workflows/preflight-dependencies.yml@89ff06bc761f0c0491d87a766eccce5aae6190ea # main

  todo-comments:
    name: Todo comments
    permissions:
      contents: read
    uses: hashintel/.github/.github/workflows/preflight-todo-comments.yml@89ff06bc761f0c0491d87a766eccce5aae6190ea # main

  pr-title:
    name: PR title
    permissions:
      contents: read
    uses: hashintel/.github/.github/workflows/preflight-pr-title.yml@89ff06bc761f0c0491d87a766eccce5aae6190ea # main
